name: Periodic Checks

on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  periodic-checks:
    needs: notify-start

    uses: ./.github/workflows/automation_exec.yml
    with:
      log_level: info
      suite: ci.periodic
      max_instances: 3
      chrome_instances: 2
      browser_visible: true
      enable_video: false
      update_report: true
